version: '3'

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    hostname: b8a4e529d211
    user: sonarqube
    environment:
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JAVA_HOME=/opt/java/openjdk
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_VERSION=jdk-17.0.9+9
      - SONARQUBE_HOME=/opt/sonarqube
      - SONAR_VERSION=9.9.2.77730
      - SQ_DATA_DIR=/opt/sonarqube/data
      - SQ_EXTENSIONS_DIR=/opt/sonarqube/extensions
      - SQ_LOGS_DIR=/opt/sonarqube/logs
      - SQ_TEMP_DIR=/opt/sonarqube/temp
    working_dir: /opt/sonarqube
    ports:
      - '9000:9000'
    restart: no
    labels:
      - org.opencontainers.image.ref.name=ubuntu
      - org.opencontainers.image.url=https://github.com/SonarSource/docker-sonarqube
      - org.opencontainers.image.version=22.04
    runtime: runc

  postgres-database:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: true

#docker exec -it tormes-backend-postgres-database-1 psql -U sergio -d my_db
